name: Deploy to Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Deploy to Vercel
        env:
          VERCEL_ORG_ID: team_nH74DsGJuHIdmakgZap16v9s
          VERCEL_PROJECT_ID: prj_qC5CHqTqH6nAtpEzOBNE9GeGs19S
        run: npx vercel deploy --prod --yes --token="${{ secrets.VERCEL_TOKEN }}"
